version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: 'cli-test'
          command: |
            sudo apt-get update
            sudo apt-get -y install awscli

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
